import { AuditAction } from '@/lib/constants'

export interface MockAuditLog {
  id: string
  userId: string
  userName: string
  userRole: string
  action: AuditAction
  resource: string
  resourceId: string | null
  resourceName: string
  details: Record<string, unknown>
  ipAddress: string
  userAgent: string
  storeId: string | null
  storeName: string | null
  result: 'success' | 'failure' | 'warning'
  timestamp: string
  sessionId: string
}

export const mockAuditLogs: MockAuditLog[] = [
  {
    id: 'audit-001',
    userId: 'user-001',
    userName: 'Carlos Rodriguez',
    userRole: 'ADMIN',
    action: AuditAction.LOGIN,
    resource: 'session',
    resourceId: null,
    resourceName: 'Sistema',
    details: { method: 'email_password', mfa: true },
    ipAddress: '83.42.115.201',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0',
    storeId: null,
    storeName: null,
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    sessionId: 'sess-abc123',
  },
  {
    id: 'audit-002',
    userId: 'user-002',
    userName: 'Ana Garcia',
    userRole: 'MANAGER',
    action: AuditAction.UPDATE,
    resource: 'product',
    resourceId: 'prod-001',
    resourceName: 'CBD Oil 10%',
    details: { field: 'price', before: 29.99, after: 34.99, reason: 'Ajuste de mercado' },
    ipAddress: '91.183.72.45',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Safari/605.1',
    storeId: '1',
    storeName: 'Madrid Centro',
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    sessionId: 'sess-def456',
  },
  {
    id: 'audit-003',
    userId: 'user-003',
    userName: 'Pedro Lopez',
    userRole: 'EMPLOYEE',
    action: AuditAction.CREATE,
    resource: 'order',
    resourceId: 'ord-1205',
    resourceName: 'Pedido #ORD-2024-1205',
    details: { items: 3, total: 189.90, customer: 'Carlos Martinez', paymentMethod: 'card' },
    ipAddress: '85.56.201.33',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/121.0',
    storeId: '2',
    storeName: 'Valencia Puerto',
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    sessionId: 'sess-ghi789',
  },
  {
    id: 'audit-004',
    userId: 'user-004',
    userName: 'Maria Fernandez',
    userRole: 'ACCOUNTING',
    action: AuditAction.EXPORT,
    resource: 'report',
    resourceId: 'rep-monthly-dec',
    resourceName: 'Reporte Mensual Diciembre',
    details: { format: 'PDF', pages: 24, dateRange: '2024-12-01/2024-12-31' },
    ipAddress: '79.108.44.12',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0',
    storeId: null,
    storeName: null,
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    sessionId: 'sess-jkl012',
  },
  {
    id: 'audit-005',
    userId: 'user-005',
    userName: 'Luis Martinez',
    userRole: 'MANAGER',
    action: AuditAction.DELETE,
    resource: 'product',
    resourceId: 'prod-045',
    resourceName: 'CBD Gummies (Descontinuado)',
    details: { reason: 'Producto descontinuado', stockRemaining: 0 },
    ipAddress: '88.24.156.78',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Chrome/120.0',
    storeId: '3',
    storeName: 'Barcelona Gotico',
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    sessionId: 'sess-mno345',
  },
  {
    id: 'audit-006',
    userId: 'user-001',
    userName: 'Carlos Rodriguez',
    userRole: 'ADMIN',
    action: AuditAction.UPDATE,
    resource: 'user',
    resourceId: 'user-008',
    resourceName: 'Miguel Sanchez',
    details: { field: 'role', before: 'EMPLOYEE', after: 'MANAGER', store: 'Barcelona Gotico' },
    ipAddress: '83.42.115.201',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0',
    storeId: '3',
    storeName: 'Barcelona Gotico',
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 42).toISOString(),
    sessionId: 'sess-abc123',
  },
  {
    id: 'audit-007',
    userId: 'user-006',
    userName: 'Elena Torres',
    userRole: 'MARKETING',
    action: AuditAction.CREATE,
    resource: 'campaign',
    resourceId: 'camp-015',
    resourceName: 'Campana Navidad 2024',
    details: { type: 'EMAIL', audience: 'VIP', budget: 2500 },
    ipAddress: '92.178.55.201',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Safari/605.1',
    storeId: null,
    storeName: null,
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    sessionId: 'sess-pqr678',
  },
  {
    id: 'audit-008',
    userId: 'user-007',
    userName: 'Roberto Diaz',
    userRole: 'EMPLOYEE',
    action: AuditAction.LOGIN,
    resource: 'session',
    resourceId: null,
    resourceName: 'Sistema',
    details: { method: 'email_password', mfa: false, failReason: 'invalid_password' },
    ipAddress: '77.231.88.45',
    userAgent: 'Mozilla/5.0 (Linux; Android 14) Chrome/120.0',
    storeId: null,
    storeName: null,
    result: 'failure',
    timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    sessionId: 'sess-none',
  },
  {
    id: 'audit-009',
    userId: 'user-002',
    userName: 'Ana Garcia',
    userRole: 'MANAGER',
    action: AuditAction.CREATE,
    resource: 'transfer',
    resourceId: 'trf-090',
    resourceName: 'Transferencia TRF-2024-090',
    details: { from: 'Alicante Marina', to: 'Madrid Centro', items: 5, totalUnits: 120 },
    ipAddress: '91.183.72.45',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Safari/605.1',
    storeId: '4',
    storeName: 'Alicante Marina',
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    sessionId: 'sess-def456',
  },
  {
    id: 'audit-010',
    userId: 'user-003',
    userName: 'Pedro Lopez',
    userRole: 'EMPLOYEE',
    action: AuditAction.READ,
    resource: 'customer',
    resourceId: 'cust-089',
    resourceName: 'Laura Fernandez',
    details: { fields: ['email', 'phone', 'purchases'], purpose: 'customer_service' },
    ipAddress: '85.56.201.33',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/121.0',
    storeId: '2',
    storeName: 'Valencia Puerto',
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    sessionId: 'sess-ghi789',
  },
  {
    id: 'audit-011',
    userId: 'user-001',
    userName: 'Carlos Rodriguez',
    userRole: 'ADMIN',
    action: AuditAction.UPDATE,
    resource: 'settings',
    resourceId: 'settings-global',
    resourceName: 'Configuracion Global',
    details: { field: 'tax_rate', before: 21, after: 21, section: 'fiscal' },
    ipAddress: '83.42.115.201',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0',
    storeId: null,
    storeName: null,
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 105).toISOString(),
    sessionId: 'sess-abc123',
  },
  {
    id: 'audit-012',
    userId: 'user-008',
    userName: 'Miguel Sanchez',
    userRole: 'EMPLOYEE',
    action: AuditAction.CREATE,
    resource: 'order',
    resourceId: 'ord-1204',
    resourceName: 'Pedido #ORD-2024-1204',
    details: { items: 2, total: 67.50, customer: 'Anonimo', paymentMethod: 'cash' },
    ipAddress: '84.77.129.56',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0',
    storeId: '3',
    storeName: 'Barcelona Gotico',
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    sessionId: 'sess-stu901',
  },
  {
    id: 'audit-013',
    userId: 'user-004',
    userName: 'Maria Fernandez',
    userRole: 'ACCOUNTING',
    action: AuditAction.EXPORT,
    resource: 'report',
    resourceId: 'rep-sales-weekly',
    resourceName: 'Reporte Ventas Semanal',
    details: { format: 'CSV', rows: 1250, stores: ['Madrid Centro', 'Valencia Puerto'] },
    ipAddress: '79.108.44.12',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0',
    storeId: null,
    storeName: null,
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
    sessionId: 'sess-jkl012',
  },
  {
    id: 'audit-014',
    userId: 'user-005',
    userName: 'Luis Martinez',
    userRole: 'MANAGER',
    action: AuditAction.UPDATE,
    resource: 'inventory',
    resourceId: 'inv-078',
    resourceName: 'Crema CBD 200ml',
    details: { field: 'quantity', before: 45, after: 50, reason: 'Recepcion proveedor' },
    ipAddress: '88.24.156.78',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Chrome/120.0',
    storeId: '3',
    storeName: 'Barcelona Gotico',
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 160).toISOString(),
    sessionId: 'sess-mno345',
  },
  {
    id: 'audit-015',
    userId: 'user-007',
    userName: 'Roberto Diaz',
    userRole: 'EMPLOYEE',
    action: AuditAction.LOGIN,
    resource: 'session',
    resourceId: null,
    resourceName: 'Sistema',
    details: { method: 'email_password', mfa: false },
    ipAddress: '77.231.88.45',
    userAgent: 'Mozilla/5.0 (Linux; Android 14) Chrome/120.0',
    storeId: null,
    storeName: null,
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    sessionId: 'sess-vwx234',
  },
  {
    id: 'audit-016',
    userId: 'user-002',
    userName: 'Ana Garcia',
    userRole: 'MANAGER',
    action: AuditAction.DELETE,
    resource: 'customer',
    resourceId: 'cust-102',
    resourceName: 'Cliente Test',
    details: { reason: 'Solicitud GDPR', dataErased: true },
    ipAddress: '91.183.72.45',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Safari/605.1',
    storeId: '1',
    storeName: 'Madrid Centro',
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    sessionId: 'sess-def456',
  },
  {
    id: 'audit-017',
    userId: 'user-009',
    userName: 'Sara Ruiz',
    userRole: 'EMPLOYEE',
    action: AuditAction.CREATE,
    resource: 'order',
    resourceId: 'ord-1203',
    resourceName: 'Pedido #ORD-2024-1203',
    details: { items: 1, total: 45.00, customer: 'Lucia Moreno', paymentMethod: 'card' },
    ipAddress: '90.174.22.89',
    userAgent: 'Mozilla/5.0 (iPad; CPU OS 17_0) AppleWebKit/605.1',
    storeId: '5',
    storeName: 'Sevilla Triana',
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 220).toISOString(),
    sessionId: 'sess-yza567',
  },
  {
    id: 'audit-018',
    userId: 'user-001',
    userName: 'Carlos Rodriguez',
    userRole: 'ADMIN',
    action: AuditAction.CREATE,
    resource: 'user',
    resourceId: 'user-010',
    resourceName: 'Pablo Navarro',
    details: { role: 'EMPLOYEE', store: 'Alicante Marina', email: 'pablo@cbd-saas.com' },
    ipAddress: '83.42.115.201',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0',
    storeId: '4',
    storeName: 'Alicante Marina',
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    sessionId: 'sess-abc123',
  },
  {
    id: 'audit-019',
    userId: 'user-006',
    userName: 'Elena Torres',
    userRole: 'MARKETING',
    action: AuditAction.UPDATE,
    resource: 'campaign',
    resourceId: 'camp-012',
    resourceName: 'Descuentos Black Friday',
    details: { field: 'status', before: 'ACTIVE', after: 'COMPLETED', conversions: 234 },
    ipAddress: '92.178.55.201',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Safari/605.1',
    storeId: null,
    storeName: null,
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 280).toISOString(),
    sessionId: 'sess-pqr678',
  },
  {
    id: 'audit-020',
    userId: 'user-003',
    userName: 'Pedro Lopez',
    userRole: 'EMPLOYEE',
    action: AuditAction.UPDATE,
    resource: 'inventory',
    resourceId: 'inv-034',
    resourceName: 'CBD Oil Premium 15%',
    details: { field: 'quantity', before: 12, after: 8, reason: 'Venta directa' },
    ipAddress: '85.56.201.33',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/121.0',
    storeId: '2',
    storeName: 'Valencia Puerto',
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    sessionId: 'sess-ghi789',
  },
  {
    id: 'audit-021',
    userId: 'user-005',
    userName: 'Luis Martinez',
    userRole: 'MANAGER',
    action: AuditAction.READ,
    resource: 'report',
    resourceId: 'rep-inventory',
    resourceName: 'Reporte de Inventario',
    details: { store: 'Barcelona Gotico', filters: { status: 'LOW' } },
    ipAddress: '88.24.156.78',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Chrome/120.0',
    storeId: '3',
    storeName: 'Barcelona Gotico',
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 330).toISOString(),
    sessionId: 'sess-mno345',
  },
  {
    id: 'audit-022',
    userId: 'user-001',
    userName: 'Carlos Rodriguez',
    userRole: 'ADMIN',
    action: AuditAction.DELETE,
    resource: 'user',
    resourceId: 'user-011',
    resourceName: 'Empleado Inactivo',
    details: { reason: 'Baja voluntaria', lastActive: '2024-10-15' },
    ipAddress: '83.42.115.201',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0',
    storeId: null,
    storeName: null,
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    sessionId: 'sess-abc123',
  },
  {
    id: 'audit-023',
    userId: 'user-007',
    userName: 'Roberto Diaz',
    userRole: 'EMPLOYEE',
    action: AuditAction.LOGOUT,
    resource: 'session',
    resourceId: null,
    resourceName: 'Sistema',
    details: { duration: '4h 23m', actionsPerformed: 45 },
    ipAddress: '77.231.88.45',
    userAgent: 'Mozilla/5.0 (Linux; Android 14) Chrome/120.0',
    storeId: null,
    storeName: null,
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 390).toISOString(),
    sessionId: 'sess-vwx234',
  },
  {
    id: 'audit-024',
    userId: 'user-004',
    userName: 'Maria Fernandez',
    userRole: 'ACCOUNTING',
    action: AuditAction.READ,
    resource: 'financial',
    resourceId: 'fin-q4-2024',
    resourceName: 'Balance Q4 2024',
    details: { sections: ['income', 'expenses', 'margins'], stores: 'all' },
    ipAddress: '79.108.44.12',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0',
    storeId: null,
    storeName: null,
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
    sessionId: 'sess-jkl012',
  },
  {
    id: 'audit-025',
    userId: 'user-002',
    userName: 'Ana Garcia',
    userRole: 'MANAGER',
    action: AuditAction.UPDATE,
    resource: 'transfer',
    resourceId: 'trf-089',
    resourceName: 'Transferencia TRF-2024-089',
    details: { field: 'status', before: 'APPROVED', after: 'IN_TRANSIT' },
    ipAddress: '91.183.72.45',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Safari/605.1',
    storeId: '3',
    storeName: 'Barcelona Gotico',
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 450).toISOString(),
    sessionId: 'sess-def456',
  },
  {
    id: 'audit-026',
    userId: 'user-008',
    userName: 'Miguel Sanchez',
    userRole: 'EMPLOYEE',
    action: AuditAction.CREATE,
    resource: 'customer',
    resourceId: 'cust-156',
    resourceName: 'Jorge Perez',
    details: { email: 'jorge@email.com', loyaltyEnrolled: true, store: 'Barcelona Gotico' },
    ipAddress: '84.77.129.56',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0',
    storeId: '3',
    storeName: 'Barcelona Gotico',
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 480).toISOString(),
    sessionId: 'sess-stu901',
  },
  {
    id: 'audit-027',
    userId: 'user-001',
    userName: 'Carlos Rodriguez',
    userRole: 'ADMIN',
    action: AuditAction.EXPORT,
    resource: 'users',
    resourceId: null,
    resourceName: 'Lista de Usuarios',
    details: { format: 'JSON', count: 28, includeInactive: false },
    ipAddress: '83.42.115.201',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0',
    storeId: null,
    storeName: null,
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 510).toISOString(),
    sessionId: 'sess-abc123',
  },
  {
    id: 'audit-028',
    userId: 'user-009',
    userName: 'Sara Ruiz',
    userRole: 'EMPLOYEE',
    action: AuditAction.UPDATE,
    resource: 'order',
    resourceId: 'ord-1198',
    resourceName: 'Pedido #ORD-2024-1198',
    details: { field: 'status', before: 'PREPARING', after: 'SHIPPED', tracking: 'ES2024891234' },
    ipAddress: '90.174.22.89',
    userAgent: 'Mozilla/5.0 (iPad; CPU OS 17_0) AppleWebKit/605.1',
    storeId: '5',
    storeName: 'Sevilla Triana',
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 540).toISOString(),
    sessionId: 'sess-yza567',
  },
  {
    id: 'audit-029',
    userId: 'user-005',
    userName: 'Luis Martinez',
    userRole: 'MANAGER',
    action: AuditAction.CREATE,
    resource: 'product',
    resourceId: 'prod-048',
    resourceName: 'CBD Balsamo Deportivo',
    details: { category: 'cosmetics', price: 39.99, sku: 'CBD-BALM-SPORT-01' },
    ipAddress: '88.24.156.78',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Chrome/120.0',
    storeId: '3',
    storeName: 'Barcelona Gotico',
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
    sessionId: 'sess-mno345',
  },
  {
    id: 'audit-030',
    userId: 'user-006',
    userName: 'Elena Torres',
    userRole: 'MARKETING',
    action: AuditAction.READ,
    resource: 'customer',
    resourceId: null,
    resourceName: 'Segmento VIP',
    details: { segment: 'VIP', count: 156, purpose: 'campaign_targeting' },
    ipAddress: '92.178.55.201',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Safari/605.1',
    storeId: null,
    storeName: null,
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 660).toISOString(),
    sessionId: 'sess-pqr678',
  },
  {
    id: 'audit-031',
    userId: 'user-003',
    userName: 'Pedro Lopez',
    userRole: 'EMPLOYEE',
    action: AuditAction.LOGIN,
    resource: 'session',
    resourceId: null,
    resourceName: 'Sistema',
    details: { method: 'email_password', mfa: false, failReason: 'account_locked' },
    ipAddress: '85.56.201.33',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/121.0',
    storeId: null,
    storeName: null,
    result: 'failure',
    timestamp: new Date(Date.now() - 1000 * 60 * 720).toISOString(),
    sessionId: 'sess-none',
  },
  {
    id: 'audit-032',
    userId: 'user-001',
    userName: 'Carlos Rodriguez',
    userRole: 'ADMIN',
    action: AuditAction.UPDATE,
    resource: 'store',
    resourceId: 'store-5',
    resourceName: 'Sevilla Triana',
    details: { field: 'phone', before: '+34 955 111 222', after: '+34 955 333 444' },
    ipAddress: '83.42.115.201',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0',
    storeId: '5',
    storeName: 'Sevilla Triana',
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 780).toISOString(),
    sessionId: 'sess-abc123',
  },
  {
    id: 'audit-033',
    userId: 'user-002',
    userName: 'Ana Garcia',
    userRole: 'MANAGER',
    action: AuditAction.EXPORT,
    resource: 'inventory',
    resourceId: null,
    resourceName: 'Inventario Madrid Centro',
    details: { format: 'CSV', rows: 89, store: 'Madrid Centro' },
    ipAddress: '91.183.72.45',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Safari/605.1',
    storeId: '1',
    storeName: 'Madrid Centro',
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 840).toISOString(),
    sessionId: 'sess-def456',
  },
  {
    id: 'audit-034',
    userId: 'user-008',
    userName: 'Miguel Sanchez',
    userRole: 'EMPLOYEE',
    action: AuditAction.UPDATE,
    resource: 'product',
    resourceId: 'prod-012',
    resourceName: 'Aceite CBD 5%',
    details: { field: 'description', before: 'Aceite basico', after: 'Aceite CBD espectro completo 5%' },
    ipAddress: '84.77.129.56',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0',
    storeId: '3',
    storeName: 'Barcelona Gotico',
    result: 'warning',
    timestamp: new Date(Date.now() - 1000 * 60 * 900).toISOString(),
    sessionId: 'sess-stu901',
  },
  {
    id: 'audit-035',
    userId: 'user-004',
    userName: 'Maria Fernandez',
    userRole: 'ACCOUNTING',
    action: AuditAction.LOGIN,
    resource: 'session',
    resourceId: null,
    resourceName: 'Sistema',
    details: { method: 'email_password', mfa: true },
    ipAddress: '79.108.44.12',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0',
    storeId: null,
    storeName: null,
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 960).toISOString(),
    sessionId: 'sess-bcd890',
  },
  {
    id: 'audit-036',
    userId: 'user-001',
    userName: 'Carlos Rodriguez',
    userRole: 'ADMIN',
    action: AuditAction.UPDATE,
    resource: 'settings',
    resourceId: 'settings-security',
    resourceName: 'Configuracion de Seguridad',
    details: { field: 'mfa_required', before: false, after: true, scope: 'admin_roles' },
    ipAddress: '83.42.115.201',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0',
    storeId: null,
    storeName: null,
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 1020).toISOString(),
    sessionId: 'sess-abc123',
  },
  {
    id: 'audit-037',
    userId: 'user-009',
    userName: 'Sara Ruiz',
    userRole: 'EMPLOYEE',
    action: AuditAction.LOGOUT,
    resource: 'session',
    resourceId: null,
    resourceName: 'Sistema',
    details: { duration: '6h 45m', actionsPerformed: 67 },
    ipAddress: '90.174.22.89',
    userAgent: 'Mozilla/5.0 (iPad; CPU OS 17_0) AppleWebKit/605.1',
    storeId: null,
    storeName: null,
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 1080).toISOString(),
    sessionId: 'sess-yza567',
  },
  {
    id: 'audit-038',
    userId: 'user-005',
    userName: 'Luis Martinez',
    userRole: 'MANAGER',
    action: AuditAction.DELETE,
    resource: 'transfer',
    resourceId: 'trf-085',
    resourceName: 'Transferencia TRF-2024-085',
    details: { reason: 'Stock insuficiente en origen', status: 'CANCELLED' },
    ipAddress: '88.24.156.78',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Chrome/120.0',
    storeId: '3',
    storeName: 'Barcelona Gotico',
    result: 'warning',
    timestamp: new Date(Date.now() - 1000 * 60 * 1140).toISOString(),
    sessionId: 'sess-mno345',
  },
  {
    id: 'audit-039',
    userId: 'user-006',
    userName: 'Elena Torres',
    userRole: 'MARKETING',
    action: AuditAction.DELETE,
    resource: 'campaign',
    resourceId: 'camp-009',
    resourceName: 'Campana Test Eliminada',
    details: { reason: 'Draft no utilizado', status: 'DRAFT' },
    ipAddress: '92.178.55.201',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Safari/605.1',
    storeId: null,
    storeName: null,
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 1200).toISOString(),
    sessionId: 'sess-pqr678',
  },
  {
    id: 'audit-040',
    userId: 'user-002',
    userName: 'Ana Garcia',
    userRole: 'MANAGER',
    action: AuditAction.CREATE,
    resource: 'order',
    resourceId: 'ord-1202',
    resourceName: 'Pedido #ORD-2024-1202',
    details: { items: 5, total: 312.50, customer: 'Empresa CBD Madrid SL', type: 'wholesale' },
    ipAddress: '91.183.72.45',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Safari/605.1',
    storeId: '1',
    storeName: 'Madrid Centro',
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 1260).toISOString(),
    sessionId: 'sess-def456',
  },
  {
    id: 'audit-041',
    userId: 'user-001',
    userName: 'Carlos Rodriguez',
    userRole: 'ADMIN',
    action: AuditAction.LOGOUT,
    resource: 'session',
    resourceId: null,
    resourceName: 'Sistema',
    details: { duration: '8h 12m', actionsPerformed: 134 },
    ipAddress: '83.42.115.201',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0',
    storeId: null,
    storeName: null,
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 1320).toISOString(),
    sessionId: 'sess-abc123',
  },
  {
    id: 'audit-042',
    userId: 'user-003',
    userName: 'Pedro Lopez',
    userRole: 'EMPLOYEE',
    action: AuditAction.CREATE,
    resource: 'customer',
    resourceId: 'cust-157',
    resourceName: 'Isabel Navarro',
    details: { email: 'isabel@email.com', loyaltyEnrolled: true, referrer: 'cust-089' },
    ipAddress: '85.56.201.33',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/121.0',
    storeId: '2',
    storeName: 'Valencia Puerto',
    result: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 1380).toISOString(),
    sessionId: 'sess-ghi789',
  },
]

// Helper functions
export function getActionLabel(action: AuditAction): string {
  switch (action) {
    case AuditAction.CREATE: return 'Crear'
    case AuditAction.READ: return 'Leer'
    case AuditAction.UPDATE: return 'Actualizar'
    case AuditAction.DELETE: return 'Eliminar'
    case AuditAction.LOGIN: return 'Iniciar Sesion'
    case AuditAction.LOGOUT: return 'Cerrar Sesion'
    case AuditAction.EXPORT: return 'Exportar'
  }
}

export function getActionColor(action: AuditAction): string {
  switch (action) {
    case AuditAction.CREATE: return 'text-cbd-green'
    case AuditAction.READ: return 'text-blue-400'
    case AuditAction.UPDATE: return 'text-amber-400'
    case AuditAction.DELETE: return 'text-red-400'
    case AuditAction.LOGIN: return 'text-emerald-400'
    case AuditAction.LOGOUT: return 'text-gray-400'
    case AuditAction.EXPORT: return 'text-purple-400'
  }
}

export function getResultColor(result: MockAuditLog['result']): string {
  switch (result) {
    case 'success': return 'text-cbd-green'
    case 'failure': return 'text-red-400'
    case 'warning': return 'text-amber-400'
  }
}

export function getResultLabel(result: MockAuditLog['result']): string {
  switch (result) {
    case 'success': return 'Exitoso'
    case 'failure': return 'Fallido'
    case 'warning': return 'Advertencia'
  }
}
