import { Product } from '@/types'

export const mockProducts: Product[] = [
  // Oils (4 products)
  {
    id: 'prod-001',
    sku: 'OIL-7K3MN2PQ',
    name: 'Aceite CBD Premium 5%',
    description: 'Aceite de CBD de espectro completo con 5% de concentracion. Extraido de canamo organico cultivado en Europa. Ideal para principiantes.',
    category: 'oils',
    brand: 'GreenVita',
    price: 29.99,
    cost: 12.50,
    margin: 58.32,
    images: ['/images/products/oil-5.jpg'],
    isActive: true,
    concentration: '5% CBD',
    composition: 'Aceite MCT, Extracto de canamo, Terpenos naturales',
    batchNumber: 'LOT-2024-OIL-001',
    certifications: ['GMP', 'Organico UE', 'ISO 9001'],
    laboratoryTests: 'https://lab.greenvita.es/reports/OIL-5-2024',
    regulatoryStatus: 'approved',
    territorialRestrictions: [],
    requiresAgeVerification: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'prod-002',
    sku: 'OIL-9R4XT6WB',
    name: 'Aceite CBD Intenso 10%',
    description: 'Aceite de CBD de alta concentracion para usuarios experimentados. Formula de espectro completo con terpenos preservados.',
    category: 'oils',
    brand: 'GreenVita',
    price: 49.99,
    cost: 20.00,
    margin: 59.99,
    images: ['/images/products/oil-10.jpg'],
    isActive: true,
    concentration: '10% CBD',
    composition: 'Aceite de oliva virgen extra, Extracto de canamo, CBG, Terpenos',
    batchNumber: 'LOT-2024-OIL-002',
    certifications: ['GMP', 'Organico UE', 'ISO 9001', 'GACP'],
    laboratoryTests: 'https://lab.greenvita.es/reports/OIL-10-2024',
    regulatoryStatus: 'approved',
    territorialRestrictions: [],
    requiresAgeVerification: true,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-03-05'),
  },
  {
    id: 'prod-003',
    sku: 'OIL-2H8YP5CZ',
    name: 'Aceite CBD Ultra 20%',
    description: 'Nuestra formula mas potente. Aceite CBD de espectro completo al 20%. Recomendado para uso terapeutico bajo supervision.',
    category: 'oils',
    brand: 'GreenVita',
    price: 89.99,
    cost: 38.00,
    margin: 57.77,
    images: ['/images/products/oil-20.jpg'],
    isActive: true,
    concentration: '20% CBD',
    composition: 'Aceite MCT, Destilado de CBD, CBN, CBG, Terpenos naturales',
    batchNumber: 'LOT-2024-OIL-003',
    certifications: ['GMP', 'ISO 9001', 'GACP'],
    laboratoryTests: 'https://lab.greenvita.es/reports/OIL-20-2024',
    regulatoryStatus: 'approved',
    territorialRestrictions: ['Canarias'],
    requiresAgeVerification: true,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: 'prod-004',
    sku: 'OIL-6D4JL9VN',
    name: 'Aceite CBD Mascotas 3%',
    description: 'Formulado especificamente para mascotas. Baja concentracion de CBD con aceite de salmon para facilitar la administracion.',
    category: 'oils',
    brand: 'PetCBD',
    price: 24.99,
    cost: 10.00,
    margin: 59.98,
    images: ['/images/products/oil-pets.jpg'],
    isActive: true,
    concentration: '3% CBD',
    composition: 'Aceite de salmon, Extracto de canamo, Vitamina E',
    batchNumber: 'LOT-2024-PET-001',
    certifications: ['GMP', 'Veterinario aprobado'],
    laboratoryTests: 'https://lab.greenvita.es/reports/PET-3-2024',
    regulatoryStatus: 'approved',
    territorialRestrictions: [],
    requiresAgeVerification: false,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-03-15'),
  },

  // Cosmetics (3 products)
  {
    id: 'prod-005',
    sku: 'COS-3F7KW2RT',
    name: 'Serum Facial CBD Anti-edad',
    description: 'Serum facial con CBD y acido hialuronico. Combate los signos del envejecimiento y proporciona hidratacion profunda.',
    category: 'cosmetics',
    brand: 'CBDBeauty',
    price: 45.99,
    cost: 18.50,
    margin: 59.77,
    images: ['/images/products/serum-facial.jpg'],
    isActive: true,
    concentration: '2% CBD',
    composition: 'Agua termal, Acido hialuronico, CBD, Vitamina C, Retinol',
    batchNumber: 'LOT-2024-COS-001',
    certifications: ['CPNP', 'Cruelty Free', 'Vegano'],
    laboratoryTests: 'https://lab.cbdbeauty.es/reports/SERUM-2024',
    regulatoryStatus: 'approved',
    territorialRestrictions: [],
    requiresAgeVerification: false,
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'prod-006',
    sku: 'COS-8M2NQ4XP',
    name: 'Balsamo Labial CBD',
    description: 'Balsamo labial nutritivo con CBD y manteca de karite. Hidratacion duradera con proteccion solar SPF15.',
    category: 'cosmetics',
    brand: 'CBDBeauty',
    price: 12.99,
    cost: 4.50,
    margin: 65.36,
    images: ['/images/products/lip-balm.jpg'],
    isActive: true,
    concentration: '1% CBD',
    composition: 'Manteca de karite, Cera de abeja, CBD, SPF15, Vitamina E',
    batchNumber: 'LOT-2024-COS-002',
    certifications: ['CPNP', 'Cruelty Free'],
    laboratoryTests: 'https://lab.cbdbeauty.es/reports/LIP-2024',
    regulatoryStatus: 'approved',
    territorialRestrictions: [],
    requiresAgeVerification: false,
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-03-12'),
  },
  {
    id: 'prod-007',
    sku: 'COS-5T9YR7HA',
    name: 'Crema Contorno de Ojos CBD',
    description: 'Tratamiento antiojeras con CBD y cafeina. Reduce bolsas y ojeras visiblemente en 4 semanas.',
    category: 'cosmetics',
    brand: 'CBDBeauty',
    price: 38.99,
    cost: 16.00,
    margin: 58.96,
    images: ['/images/products/eye-cream.jpg'],
    isActive: false,
    concentration: '1.5% CBD',
    composition: 'Agua micelar, CBD, Cafeina, Peptidos, Acido hialuronico',
    batchNumber: 'LOT-2024-COS-003',
    certifications: ['CPNP', 'Cruelty Free', 'Vegano'],
    laboratoryTests: 'https://lab.cbdbeauty.es/reports/EYE-2024',
    regulatoryStatus: 'pending',
    territorialRestrictions: [],
    requiresAgeVerification: false,
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-03-18'),
  },

  // Flowers (3 products)
  {
    id: 'prod-008',
    sku: 'FLO-4G6ZS8BV',
    name: 'Flores CBD Amnesia Haze',
    description: 'Flores de CBD de la variedad Amnesia Haze. Cultivo indoor, cogollos densos con aromas citricos y terrosos.',
    category: 'flowers',
    brand: 'HempFlowers',
    price: 8.99,
    cost: 3.50,
    margin: 61.07,
    images: ['/images/products/flower-amnesia.jpg'],
    isActive: true,
    concentration: '12% CBD / <0.2% THC',
    composition: 'Flores de cannabis sativa L., Terpenos: Limoneno, Mirceno, Pineno',
    batchNumber: 'LOT-2024-FLO-001',
    certifications: ['EU Hemp Certified', 'Analisis COA'],
    laboratoryTests: 'https://lab.hempflowers.es/reports/AMNESIA-2024',
    regulatoryStatus: 'approved',
    territorialRestrictions: ['Pais Vasco'],
    requiresAgeVerification: true,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'prod-009',
    sku: 'FLO-7L3XC5DW',
    name: 'Flores CBD OG Kush',
    description: 'Variedad OG Kush con alto contenido en CBD. Perfil terpenico complejo con notas de pino y limon.',
    category: 'flowers',
    brand: 'HempFlowers',
    price: 9.99,
    cost: 4.00,
    margin: 59.96,
    images: ['/images/products/flower-ogkush.jpg'],
    isActive: true,
    concentration: '15% CBD / <0.2% THC',
    composition: 'Flores de cannabis sativa L., Terpenos: Cariofileno, Limoneno, Humuleno',
    batchNumber: 'LOT-2024-FLO-002',
    certifications: ['EU Hemp Certified', 'Analisis COA', 'Cultivo Ecologico'],
    laboratoryTests: 'https://lab.hempflowers.es/reports/OGKUSH-2024',
    regulatoryStatus: 'approved',
    territorialRestrictions: ['Pais Vasco'],
    requiresAgeVerification: true,
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-03-05'),
  },
  {
    id: 'prod-010',
    sku: 'FLO-1N8JP4KE',
    name: 'Flores CBD Gorilla Glue',
    description: 'Variedad Gorilla Glue premium. Cogollos cubiertos de tricomas con aromas dulces y diesel.',
    category: 'flowers',
    brand: 'HempFlowers',
    price: 11.99,
    cost: 5.00,
    margin: 58.30,
    images: ['/images/products/flower-gorilla.jpg'],
    isActive: true,
    concentration: '18% CBD / <0.2% THC',
    composition: 'Flores de cannabis sativa L., Terpenos: Mirceno, Cariofileno, Limoneno',
    batchNumber: 'LOT-2024-FLO-003',
    certifications: ['EU Hemp Certified', 'Analisis COA'],
    laboratoryTests: 'https://lab.hempflowers.es/reports/GORILLA-2024',
    regulatoryStatus: 'under_review',
    territorialRestrictions: ['Pais Vasco', 'Canarias'],
    requiresAgeVerification: true,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-03-20'),
  },

  // Capsules (3 products)
  {
    id: 'prod-011',
    sku: 'CAP-2Q5FH7MR',
    name: 'Capsulas CBD 10mg Sueno',
    description: 'Capsulas de CBD con melatonina para mejorar la calidad del sueno. 30 capsulas por bote.',
    category: 'capsules',
    brand: 'CBDHealth',
    price: 34.99,
    cost: 14.00,
    margin: 59.99,
    images: ['/images/products/caps-sleep.jpg'],
    isActive: true,
    concentration: '10mg CBD por capsula',
    composition: 'CBD aislado, Melatonina 1mg, Gelatina vegetal, Aceite MCT',
    batchNumber: 'LOT-2024-CAP-001',
    certifications: ['GMP', 'Vegano', 'Sin gluten'],
    laboratoryTests: 'https://lab.cbdhealth.es/reports/SLEEP-2024',
    regulatoryStatus: 'approved',
    territorialRestrictions: [],
    requiresAgeVerification: true,
    createdAt: new Date('2024-01-30'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: 'prod-012',
    sku: 'CAP-6V9TW3GL',
    name: 'Capsulas CBD 25mg Concentracion',
    description: 'Formula avanzada con CBD y Bacopa Monnieri para mejorar el enfoque y la concentracion. 60 capsulas.',
    category: 'capsules',
    brand: 'CBDHealth',
    price: 54.99,
    cost: 22.00,
    margin: 60.01,
    images: ['/images/products/caps-focus.jpg'],
    isActive: true,
    concentration: '25mg CBD por capsula',
    composition: 'CBD espectro completo, Bacopa Monnieri, L-Teanina, Gelatina vegetal',
    batchNumber: 'LOT-2024-CAP-002',
    certifications: ['GMP', 'ISO 9001'],
    laboratoryTests: 'https://lab.cbdhealth.es/reports/FOCUS-2024',
    regulatoryStatus: 'approved',
    territorialRestrictions: [],
    requiresAgeVerification: true,
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 'prod-013',
    sku: 'CAP-4A8YN6SP',
    name: 'Capsulas CBD 50mg Forte',
    description: 'Alta dosis de CBD en capsulas de facil absorcion. Para usuarios con necesidades elevadas. 30 capsulas.',
    category: 'capsules',
    brand: 'CBDHealth',
    price: 79.99,
    cost: 35.00,
    margin: 56.24,
    images: ['/images/products/caps-forte.jpg'],
    isActive: true,
    concentration: '50mg CBD por capsula',
    composition: 'CBD destilado, Aceite MCT, Pimienta negra (piperina), Gelatina vegetal',
    batchNumber: 'LOT-2024-CAP-003',
    certifications: ['GMP', 'ISO 9001', 'GACP'],
    laboratoryTests: 'https://lab.cbdhealth.es/reports/FORTE-2024',
    regulatoryStatus: 'pending',
    territorialRestrictions: ['Canarias'],
    requiresAgeVerification: true,
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-03-18'),
  },

  // Creams (3 products)
  {
    id: 'prod-014',
    sku: 'CRM-8B2LK4VQ',
    name: 'Crema CBD Muscular Sport',
    description: 'Crema deportiva con CBD y arnica para alivio muscular y articular. Efecto frio-calor.',
    category: 'creams',
    brand: 'CBDSport',
    price: 32.99,
    cost: 13.50,
    margin: 59.08,
    images: ['/images/products/cream-sport.jpg'],
    isActive: true,
    concentration: '3% CBD',
    composition: 'Agua, CBD, Arnica montana, Mentol, Alcanfor, Aceite de eucalipto',
    batchNumber: 'LOT-2024-CRM-001',
    certifications: ['CPNP', 'Dermatologicamente testado'],
    laboratoryTests: 'https://lab.cbdsport.es/reports/SPORT-2024',
    regulatoryStatus: 'approved',
    territorialRestrictions: [],
    requiresAgeVerification: false,
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'prod-015',
    sku: 'CRM-5E7PD9HX',
    name: 'Crema Hidratante CBD Facial',
    description: 'Hidratante facial de uso diario con CBD y aloe vera. Para todo tipo de pieles, especialmente sensibles.',
    category: 'creams',
    brand: 'CBDBeauty',
    price: 36.99,
    cost: 15.00,
    margin: 59.45,
    images: ['/images/products/cream-facial.jpg'],
    isActive: true,
    concentration: '2% CBD',
    composition: 'Agua termal, CBD, Aloe vera, Manteca de cacao, Vitamina E, Niacinamida',
    batchNumber: 'LOT-2024-CRM-002',
    certifications: ['CPNP', 'Cruelty Free', 'Vegano', 'Dermatologicamente testado'],
    laboratoryTests: 'https://lab.cbdbeauty.es/reports/FACIAL-2024',
    regulatoryStatus: 'approved',
    territorialRestrictions: [],
    requiresAgeVerification: false,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-12'),
  },
  {
    id: 'prod-016',
    sku: 'CRM-3G1NR6WJ',
    name: 'Crema CBD Articulaciones',
    description: 'Crema especifica para articulaciones con CBD, glucosamina y condroitina. Alivio localizado.',
    category: 'creams',
    brand: 'CBDSport',
    price: 39.99,
    cost: 17.00,
    margin: 57.49,
    images: ['/images/products/cream-joint.jpg'],
    isActive: true,
    concentration: '5% CBD',
    composition: 'Agua, CBD, Glucosamina, Condroitina, MSM, Capsaicina, Aceite de romero',
    batchNumber: 'LOT-2024-CRM-003',
    certifications: ['CPNP', 'Dermatologicamente testado'],
    laboratoryTests: 'https://lab.cbdsport.es/reports/JOINT-2024',
    regulatoryStatus: 'approved',
    territorialRestrictions: [],
    requiresAgeVerification: false,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-03-15'),
  },

  // Wellness (3 products)
  {
    id: 'prod-017',
    sku: 'WEL-9C4XM7TF',
    name: 'Infusion CBD Relax',
    description: 'Te de hierbas con CBD, manzanilla y valeriana. Perfecto para relajarse antes de dormir. 20 bolsitas.',
    category: 'wellness',
    brand: 'HerbaCBD',
    price: 18.99,
    cost: 7.50,
    margin: 60.51,
    images: ['/images/products/tea-relax.jpg'],
    isActive: true,
    concentration: '5mg CBD por bolsita',
    composition: 'Manzanilla, Valeriana, Flores de canamo CBD, Lavanda, Pasiflora',
    batchNumber: 'LOT-2024-WEL-001',
    certifications: ['Organico UE', 'Vegano'],
    laboratoryTests: 'https://lab.herbacbd.es/reports/TEA-2024',
    regulatoryStatus: 'approved',
    territorialRestrictions: [],
    requiresAgeVerification: false,
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-03-05'),
  },
  {
    id: 'prod-018',
    sku: 'WEL-1D6ZQ2YP',
    name: 'Gominolas CBD Frutas 10mg',
    description: 'Gominolas veganas de CBD con sabores naturales de frutas. 30 unidades por bote. Sin azucar anadido.',
    category: 'wellness',
    brand: 'HerbaCBD',
    price: 29.99,
    cost: 11.00,
    margin: 63.32,
    images: ['/images/products/gummies.jpg'],
    isActive: true,
    concentration: '10mg CBD por gominola',
    composition: 'Pectina, CBD aislado, Zumo de frutas concentrado, Stevia, Colorantes naturales',
    batchNumber: 'LOT-2024-WEL-002',
    certifications: ['Vegano', 'Sin gluten', 'Sin azucar'],
    laboratoryTests: 'https://lab.herbacbd.es/reports/GUMMIES-2024',
    regulatoryStatus: 'approved',
    territorialRestrictions: [],
    requiresAgeVerification: true,
    createdAt: new Date('2024-02-08'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: 'prod-019',
    sku: 'WEL-7H5BK8NE',
    name: 'Proteina Whey + CBD Recovery',
    description: 'Proteina de suero con CBD para recuperacion post-entrenamiento. 750g, sabor chocolate.',
    category: 'wellness',
    brand: 'CBDSport',
    price: 54.99,
    cost: 24.00,
    margin: 56.36,
    images: ['/images/products/protein-cbd.jpg'],
    isActive: true,
    concentration: '15mg CBD por dosis',
    composition: 'Proteina de suero, CBD aislado, Cacao, Lectina de girasol, Stevia',
    batchNumber: 'LOT-2024-WEL-003',
    certifications: ['GMP', 'Informed Sport'],
    laboratoryTests: 'https://lab.cbdsport.es/reports/PROTEIN-2024',
    regulatoryStatus: 'under_review',
    territorialRestrictions: [],
    requiresAgeVerification: false,
    createdAt: new Date('2024-02-25'),
    updatedAt: new Date('2024-03-20'),
  },

  // Accessories (3 products)
  {
    id: 'prod-020',
    sku: 'ACC-4F9TL3QV',
    name: 'Vaporizador CBD Pen Starter',
    description: 'Kit de inicio de vaporizador para e-liquidos CBD. Bateria recargable USB-C, tanque 1ml.',
    category: 'accessories',
    brand: 'VapeCBD',
    price: 29.99,
    cost: 12.00,
    margin: 59.99,
    images: ['/images/products/vape-pen.jpg'],
    isActive: true,
    concentration: null,
    composition: null,
    batchNumber: 'LOT-2024-ACC-001',
    certifications: ['CE', 'RoHS'],
    laboratoryTests: null,
    regulatoryStatus: 'approved',
    territorialRestrictions: [],
    requiresAgeVerification: true,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'prod-021',
    sku: 'ACC-6R2WN8BD',
    name: 'Grinder Premium 4 piezas',
    description: 'Grinder de aluminio aeronautico de 4 piezas con recogedor de polen. Diametro 55mm.',
    category: 'accessories',
    brand: 'HempTools',
    price: 19.99,
    cost: 7.00,
    margin: 64.98,
    images: ['/images/products/grinder.jpg'],
    isActive: true,
    concentration: null,
    composition: null,
    batchNumber: 'LOT-2024-ACC-002',
    certifications: ['CE'],
    laboratoryTests: null,
    regulatoryStatus: 'approved',
    territorialRestrictions: [],
    requiresAgeVerification: true,
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-03-05'),
  },
  {
    id: 'prod-022',
    sku: 'ACC-8P4XK5MC',
    name: 'Kit Dosificacion Aceite CBD',
    description: 'Kit completo con pipetas de precision, tarjeta de dosificacion y estuche de viaje. Compatible con todos nuestros aceites.',
    category: 'accessories',
    brand: 'GreenVita',
    price: 14.99,
    cost: 5.00,
    margin: 66.64,
    images: ['/images/products/dosing-kit.jpg'],
    isActive: true,
    concentration: null,
    composition: null,
    batchNumber: 'LOT-2024-ACC-003',
    certifications: ['CE', 'Sin BPA'],
    laboratoryTests: null,
    regulatoryStatus: 'approved',
    territorialRestrictions: [],
    requiresAgeVerification: false,
    createdAt: new Date('2024-02-12'),
    updatedAt: new Date('2024-03-15'),
  },
]

// Helper to get a product by ID
export function getProductById(id: string): Product | undefined {
  return mockProducts.find((p) => p.id === id)
}

// Helper to get products by category
export function getProductsByCategory(category: string): Product[] {
  return mockProducts.filter((p) => p.category === category)
}
